services:
  - type: web
    name: finance-control
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://controle-financeiro-60w6.onrender.com
    healthCheckPath: /
    autoDeploy: true 